//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجراء حذف.
        /// </summary>
        internal static string DeleteDialogCaption {
            get {
                return ResourceManager.GetString("DeleteDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من انك تريد حذف العنصر؟.
        /// </summary>
        internal static string DeleteDialogText {
            get {
                return ResourceManager.GetString("DeleteDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيه فى عملية الحذف.
        /// </summary>
        internal static string DeleteNotificationCaption {
            get {
                return ResourceManager.GetString("DeleteNotificationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجاء اختر عنصر واحد للحذف فى المره.
        /// </summary>
        internal static string DeleteNotificationText {
            get {
                return ResourceManager.GetString("DeleteNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات.
        /// </summary>
        internal static string EmptyDataCaption {
            get {
                return ResourceManager.GetString("EmptyDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات للقيام بالعمليات عليها.
        /// </summary>
        internal static string EmptyDataText {
            get {
                return ResourceManager.GetString("EmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا ادخال.
        /// </summary>
        internal static string FiledReqCaption {
            get {
                return ResourceManager.GetString("FiledReqCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقول التى تحتوى على علامة * هى حول مطلوبه. اعد ادخالها ثم حاول مره اخرى.
        /// </summary>
        internal static string FiledReqText {
            get {
                return ResourceManager.GetString("FiledReqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات.
        /// </summary>
        internal static string NoSelectedItemsCaption {
            get {
                return ResourceManager.GetString("NoSelectedItemsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تحديد عناصر, جرب تحديد كامل السطر.
        /// </summary>
        internal static string NoSelectedItemsText {
            get {
                return ResourceManager.GetString("NoSelectedItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملية بحث.
        /// </summary>
        internal static string NotFoundCaption {
            get {
                return ResourceManager.GetString("NotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على بيانات, جرب بيانات اخرى.
        /// </summary>
        internal static string NotFoundText {
            get {
                return ResourceManager.GetString("NotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا ادخال.
        /// </summary>
        internal static string PurSellErrorCaption {
            get {
                return ResourceManager.GetString("PurSellErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد انك تريد سعر الشراء اكبر من سعر البيع؟.
        /// </summary>
        internal static string PurSellErrorText {
            get {
                return ResourceManager.GetString("PurSellErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا اتصال.
        /// </summary>
        internal static string ServerErrorCaption {
            get {
                return ResourceManager.GetString("ServerErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يبدو ان لديك خطا فى الاتصال بالسيرفر, حاول مجدادا او اعد ضبط الاتصال من خلال اعدادات النظام.
        /// </summary>
        internal static string ServerErrorText {
            get {
                return ResourceManager.GetString("ServerErrorText", resourceCulture);
            }
        }
    }
}
